from datetime import datetime
from typing import Optional, List, Annotated
from pydantic import BaseModel, Field
from pydantic.functional_validators import BeforeValidator

PyObjectId = Annotated[str, BeforeValidator(str)]


# ── Incoming payload from the frontend ──────────────────────────────────────

class PageViewCreate(BaseModel):
    """
    Sent by the frontend on every page visit (and optionally again on unload
    to update time_spent for the same session_id + page combination).
    """
    page: str = Field(..., description="Page path, e.g. '/dashboard'")
    session_id: str = Field(..., description="Unique session ID generated by the frontend")
    time_spent: Optional[float] = Field(
        default=0.0,
        description="Seconds spent on the page. Updated on page unload."
    )
    referrer: Optional[str] = Field(
        default=None,
        description="The page the user came from, e.g. '/login'"
    )
    username: str = Field(default="Guest", description="Logged-in username or 'Guest'")
    timestamp: Optional[datetime] = Field(
        default=None,
        description="ISO timestamp of the visit. Server sets this if not provided."
    )


# ── Aggregation report response models ──────────────────────────────────────

class PageVisitStat(BaseModel):
    """Top pages ranked by visit count."""
    page: str
    visits: int
    unique_sessions: int


class PageTimeStat(BaseModel):
    """Top pages ranked by time spent."""
    page: str
    total_time_seconds: float
    avg_time_seconds: float


class AnalyticsReport(BaseModel):
    """Full analytics report returned to the admin dashboard."""
    period: str
    total_pageviews: int
    top_pages_by_visits: List[PageVisitStat]
    top_pages_by_time_spent: List[PageTimeStat]
